### ISSUE TITLE
image issue

### ISSUE THREAD

**Issue by TyannaB** [TyannaB/html-validation-fixes#1]
<!DOCTYPE html>
<html lang="zxx">
<head>
  <meta charset=utf-8>
  <title>Fix Naming & Indentation Errors</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>

  <header>
  <h1>Fix these 3 poorly named files, 4 indenting issues & 3 validation errors</h1>
  </header>

  <main>
  _<**img src= "air dino.jpg" alt=**"">_
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</body>

</main>

  <footer>
    <p>© 2016 Fixing Errors Co.</p></footer></html>
@thomasjbradley

**Comment by TyannaB** [comment]
the issue i am having right now is where it says _<**img src= "air dino.jpg" alt=**"">_ because i am supposed to put an image there correct ?

**Comment by thomasjbradley** [comment]
Try fixing the "Naming convention" problems first and see if that helps out.

**Comment by TyannaB** [comment]
Okay I'll try that

Sent from my iPhone

On Sep 26, 2017, at 7:48 PM, Thomas J Bradley <notifications@github.com<mailto:notifications@github.com>> wrote:


Try fixing the "Naming convention" problems first and see if that helps out.
